const CORS_ORIGIN = "*";
const JSON_SIZE = "16kb";
const URL_PARAM_SIZE = "16kb"
const SALTING_ROUNDS = 10;
const DB_NAME="youtube";

export {CORS_ORIGIN, JSON_SIZE, URL_PARAM_SIZE, SALTING_ROUNDS, DB_NAME};